version: '3.8'

services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-spring-app  # Custom name for your Spring container
    ports:
      - "8080:8080"
    environment:
      MINIO_ENDPOINT: minio1:9000  # Pointing to your existing MinIO container
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}

# Remove the MinIO service since you already have it running
